
run:
		latexmk -pdf -pvc definitions-and-semantics

debug:
		pdflatex -shell-escape definitions-and-semantics.tex

clean:
		rm *.aux *.toc *.out *.fdb_latexmk *.fls *.log *.synctex.gz; rm -rf _minted-definitions-and-semantics/
